#!/bin/bash

#set -x

# make sure to run only once
pidof -o %PPID -x "$(basename -- "$0")" >/dev/null && echo "ERROR: Script $0 already running on " `TZ='America/Denver' date` && exit 1

echo "$0  started on `TZ='America/Denver' date`"

cd $(dirname $0)

for x in $(./getmaxid -q); do
    lastlog=log/$(echo "$x-10" | bc)-get.log
    if [ -f $lastlog ]; then
        rm $lastlog
    fi
    ./get10kio $x >log/$x-get.log
    badkeys --crt-lines v4/$x/* >badkeyslog/badkeys-$x.log
    echo | cat badkeyslog/badkeys-$x.log

done

echo "$0 finished on `TZ='America/Denver' date`"

sudo shutdown +5
