#!/bin/bash

#set -x

# make sure to run only once
pidof -o %PPID -x "$(basename -- "$0")" >/dev/null && echo "ERROR: Script $0 already running on " `TZ='America/Denver' date` && exit 1

lastdir=$(ls $(dirname $0)/v4/ | tail -n 1)
lastdir=$(echo "$lastdir-1" | bc)
echo "$(basename -- "$0") started with v4/$lastdir on `TZ='America/Denver' date`"

cd $(dirname $0)

for x in $(./getmaxid -q); do
    lastlog=log/$(echo "$x-10" | bc)-get.log
    if [ -f $lastlog ]; then
        rm $lastlog
    fi
    ./get10kio $x >log/$x-get.log
    badkeys --crt-lines v4/$x/* >badkeyslog/badkeys-$x.log
    echo | cat badkeyslog/badkeys-$x.log

done

lastdir=$(ls $(dirname $0)/v4/ | tail -n 1)
echo "$(basename -- "$0") finished with v4/$lastdir on `TZ='America/Denver' date`"

sudo shutdown +5
