#!/bin/bash

#set -x

maxid=$(echo "SELECT MAX(ID) FROM certificate" | psql --csv -t -h crt.sh -p 5432 -U guest certwatch)

[ "$1" = "-q" ] || echo "MaxID $maxid"

maxdir=$(echo "$maxid/10000" | bc)
xdir=$(ls $(dirname $0)/v4/ | tail -n 1)

if [ "$maxdir" -eq "$xdir" ]; then
    [ "$1" = "-q" ] || echo "All ok"
else
    ((xdir = xdir + 1))
    [ "$1" = "-q" ] || echo Needs $(seq $xdir 1 $maxdir)
    [ "$1" = "-q" ] && seq $xdir 1 $maxdir
fi
